### PR TITLE
Ticked version, regenerated if needed. (Double-check reqs!)

### PR DESCRIPTION
**Pull request by pmlandwehr**
Made using `tick_my_feedstocks.py`!
- [x] **I have vetted this recipe**

### CODE REVIEW

**Comment by pmlandwehr** [comment]
Seems to have issues b/c how scripts are stored has been reorged? (That is, the build failure is caused when trying `$ docx2txt -h`)

**Comment by nikicc** [comment]
> Seems to have issues b/c how scripts are stored has been reorged?

@pmlandwehr not sure what reorg do you have in mind. Checking the [diff between `0.7` and `0.6`](https://github.com/ankushshah89/python-docx2txt/compare/0.6...0.7) doesn't reveal any reorganisation.

**Comment by pmlandwehr** [comment]
"reorging" is probably a misdiagnosis on my part. CircleCI is failing when it runs `docx2txt -h` during testing, and complains that it doesn't have permission to access the script; in other cases, that's been the same as a file not being found.

**Comment by pmlandwehr** [comment]
@conda-forge-admin please rerender

**Comment by pmlandwehr** [comment]
@conda-forge-admin please rerender

**Comment by pmlandwehr** [comment]
Based on local experiments, the central issue seems to be `noarch: python`. For reasons that I don't understand, that build configuration causes the `docx2txt` command line script to be inaccessible.

**Pull request closed without merging**
